version: '3'

services:
  db:
    container_name: 'weeranut-postgres'
    ports:
      - 54322:5432
    environment:
      - POSTGRES_USER=weeranut
      - POSTGRES_PASSWORD=wutthi06
    image: 'postgres:latest'
    restart: 'unless-stopped'

  pgadmin:
    container_name: 'weeranut-pgadmin'
    ports:
      - 8080:80
    environment: 
      - PGADMIN_DEFAULT_EMAIL=weeranut-w@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=wutthi06
    image: 'dpage/pgadmin4:latest'
    restart: 'unless-stopped'

  strapi:
    container_name: 'weeranut-strapi'
    ports:
      - 1337:1337
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=192.168.56.1
      - DATABASE_PORT=54322
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=weeranut
      - DATABASE_PASSWORD=wutthi06
      - DATABASE_SSL=false
    image: 'naskio/strapi:latest'
    restart: 'unless-stopped'



  